application: cookies
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.css)
  mime_type: text/css
  static_files: bootstrap/\1
  upload: bootstrap/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: bootstrap/\1
  upload: bootstrap/(.*\.html)
  expiration: "1h"
# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: bootstrap/\1
  upload: bootstrap/(.*\.(bmp|gif|ico|jpeg|jpg|png))
 
- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: bootstrap/\1
  upload: bootstrap/(.*\.ico)
  expiration: "7d"
 
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: bootstrap/\1
  upload: bootstrap/(.*\.js)
 

- url: .*
  script: main.app

libraries:
- name: PIL
  version: latest
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"


